backend:
  name: github
  branch: main

media_folder: "apps"
public_folder: "apps"

collections:
  - name: "apps"
    label: "Apps"
    folder: "apps"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "APK File", name: "apk", widget: "file"}
